name: Simple benchmarking

on:
  workflow_dispatch:
  workflow_call:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      #max-parallel: 1
      matrix:
        luceeVersion: [ 5.4/snapshot/light, 6.0/snapshot/light, 6.1/snapshot/light, 6.1.0/snapshot/light, 6.2/snapshot/light ]
        javaVersion: [ 11, 21 ]
        exclude:
            - luceeVersion: 5.4/snapshot/light
              javaVersion: 21
            - luceeVersion: 6.0/snapshot/light
              javaVersion: 21
    env:
        luceeVersionQuery: ${{ matrix.luceeVersion }}
        compile: ${{ github.event.inputs.compile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.javaVersion}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.javaVersion}}
          distribution: "temurin"
      - name: Cache Maven packages
        if: always()
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-cache
      - name: Cache Lucee files
        uses: actions/cache@v4
        if: always()
        with:
          path: /home/runner/work/_actions/lucee/script-runner/main/lucee-download-cache
          key: lucee-downloads
      - name: Set up MySQL (local)
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE lucee' -uroot -proot
          mysql -e 'CREATE USER "lucee"@"localhost" IDENTIFIED WITH mysql_native_password BY "lucee";' -uroot -proot
          mysql -e 'GRANT ALL PRIVILEGES ON lucee.* TO "lucee"@"localhost"' -uroot -proot
      - name: Run Microbenches
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/custom/benchmark
          execute: /index.cfm
          extensions: 7E673D15-D87C-41A6-8B5F1956528C605F #mysql
          luceeVersionQuery: ${{ matrix.luceeVersion }}
      - uses: actions/upload-artifact@v4
        with:
          name: results-${{ strategy.job-index }}
          path: ${{ github.workspace }}/custom/benchmark/artifacts

  report:
    runs-on: ubuntu-latest
    needs: [ benchmarks ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
            java-version: 11
            distribution: "temurin"
      - name: Cache Maven packages
        if: always()
        uses: actions/cache@v4
        with:
            path: ~/.m2
            key: maven-cache
      - name: Cache Lucee files
        uses: actions/cache@v4
        if: always()
        with:
            path: /home/runner/work/_actions/lucee/script-runner/main/lucee-download-cache
            key: lucee-downloads
      - uses: actions/download-artifact@v4
        with:
            path: ${{ github.workspace }}/custom/benchmark/artifacts
            merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R ${{ github.workspace }}/custom/benchmark/artifacts
      - name: Generate Report
        uses: lucee/script-runner@main
        with:
            webroot: ${{ github.workspace }}/custom/benchmark
            execute: /report.cfm
            luceeVersionQuery: 5.4/stable/jar


