name: Simple benchmarking  

on:
  workflow_dispatch:
  workflow_call:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:        
        luceeVersion: [ 5.4/snapshot/light, 6.0/snapshot/light, 6.1/snapshot/light, 6.1.0/snapshot/light, 6.2/snapshot/light ]
        javaVersion: [ 11, 21 ]
        exclude: 
            - luceeVersion: 5.4/snapshot/jar
              javaVersion: 21
            - luceeVersion: 6.0/snapshot/jar
              javaVersion: 21
    env:
        luceeVersionQuery: ${{ matrix.luceeVersion }}
        compile: ${{ github.event.inputs.compile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.javaVersion}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.javaVersion}}
          distribution: "temurin"
      - name: Cache Maven packages
        if: always()
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-cache
      - name: Cache Lucee files
        uses: actions/cache@v4
        if: always()
        with:
          path: /home/runner/work/_actions/lucee/script-runner/main/lucee-download-cache
          key: lucee-downloads
      - name: Run Microbenches
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/custom/benchmark
          execute: /index.cfm
          luceeVersionQuery: ${{ matrix.luceeVersion }}
  
