name: Check Bundles  

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        luceeVersion:
          [
            5.4/snapshot/jar,
            6.0/snapshot/jar,
            6.1/snapshot/jar,
            6.1.0/snapshot/jar,
            6.2/snapshot/jar,
          ]
        javaVersion: [ 11 ]
    env:
        luceeVersionQuery: ${{ matrix.luceeVersion }}
        compile: ${{ github.event.inputs.compile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.javaVersion}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.javaVersion}}
          distribution: "temurin"
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-cache
      - name: Cache Lucee files
        uses: actions/cache@v4
        with:
          path: /home/runner/work/_actions/lucee/script-runner/main/lucee-download-cache
          key: lucee-downloads
      - name: Load Lucee and extensions with LUCEE_ENABLE_BUNDLE_DOWNLOAD disabled
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/custom/bundle-test
          execute: /index.cfm
          luceeVersionQuery: ${{ matrix.luceeVersion }}
        env:
          LUCEE_CLI_PRINTEXCEPTIONS: TRUE
          LUCEE_ENABLE_BUNDLE_DOWNLOAD: FALSE
          LUCEE_ADMIN_PASSWORD: lucee
  
