name: Check Jar Conflicts

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        luceeVersion:
          [
            5.4/snapshot/light,
            6.1.0/snapshot/light
          ]
        javaVersion: [ 11 ]
    env:
        luceeVersionQuery: ${{ matrix.luceeVersion }}
        compile: ${{ github.event.inputs.compile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.javaVersion}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.javaVersion}}
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-cache
      - name: Cache Lucee files
        if: always()
        uses: actions/cache@v4
        with:
          path: /home/runner/work/_actions/lucee/script-runner/main/lucee-download-cache
          key: lucee-downloads

      - name: Download poi Jars
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/custom/jar-conflict
          execute: /setup.cfm
          luceeVersionQuery: ${{ matrix.luceeVersion }}
          postCleanup: false
      - name: Load jars by path and libDir
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/custom/jar-conflict
          execute: /index.cfm
          luceeVersionQuery: ${{ matrix.luceeVersion }}
          preCleanup: false
        #env:
          #LUCEE_BASE_CONFIG: ${{ github.workspace }}/custom/jar-conflict/.CFConfig-jar-conflict.json
