name: Run lucee-spreadsheet test suite

on:
  [ workflow_dispatch, workflow_call ]

jobs:
  setup-lucee-spreadsheet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4 
    - name: Checkout lucee-spreadsheet Repository
      uses: actions/checkout@v4
      with:
        repository: cfsimplicity/spreadsheet-cfml
        path: src
    - name: Copy custom test runner tweaks
      run: |
        cp -R custom/lucee-spreadsheet src
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Install the ortus security key
      run: curl -fsSl https://downloads.ortussolutions.com/debs/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/ortussolutions.gpg > /dev/null

    - name: Add the commandbox source
      run: echo "deb [signed-by=/usr/share/keyrings/ortussolutions.gpg] https://downloads.ortussolutions.com/debs/noarch /" | sudo tee /etc/apt/sources.list.d/commandbox.list

    - name: Update apt and install commandbox
      run: sudo apt-get update && sudo apt-get install apt-transport-https commandbox

    - name: Install dependencies
      run: |
        cd src
        box install
    - name: installed webroot for matrix steps
      uses: actions/upload-artifact@v4
      with:
        name: webroot
        path: ${{ github.workspace }}/src
    
  tests:
    runs-on: ubuntu-latest
    needs: [ setup-lucee-spreadsheet ]
    strategy:
      fail-fast: false
      matrix:
        luceeVersion: [ 5.4/snapshot/jar, 6.0/snapshot/jar, 6.1/snapshot/jar ]
        javaVersion: [ 11, 21 ]
        exclude: 
            - luceeVersion: 5.4/snapshot/jar
              javaVersion: 21
            - luceeVersion: 6.0/snapshot/jar
              javaVersion: 21
    steps:
     - name: Restore pre-prepared webroot
       uses: actions/download-artifact@v4
       with:
         name: webroot
         path: ${{ github.workspace }}
     - name: Set up JDK ${{matrix.javaVersion}}
       uses: actions/setup-java@v4
       with:
         java-version: ${{matrix.javaVersion}}
         distribution: 'temurin'
     - name: Run Test Suite
       uses: lucee/script-runner@main
       with:
          webroot: ${{ github.workspace }}/test
          execute: /index.cfm
          luceeVersionQuery: ${{ matrix.luceeVersion }}
